"""add_research_intelligence

Revision ID: 45f4c2db259d
Revises: 20260529_0006
Create Date: 2026-05-30 14:00:53.330311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f4c2db259d'
down_revision: Union[str, Sequence[str], None] = '20260529_0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_insights_workspace_id'), 'research_insights', ['workspace_id'], unique=False)
    op.create_table('research_papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_papers_doi'), 'research_papers', ['doi'], unique=False)
    op.create_index(op.f('ix_research_papers_slug'), 'research_papers', ['slug'], unique=False)
    op.create_index(op.f('ix_research_papers_workspace_id'), 'research_papers', ['workspace_id'], unique=False)
    op.create_table('research_analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['research_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_analysis_jobs_paper_id'), 'research_analysis_jobs', ['paper_id'], unique=False)
    op.create_index(op.f('ix_research_analysis_jobs_workspace_id'), 'research_analysis_jobs', ['workspace_id'], unique=False)
    op.create_table('research_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('grounding_level', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['research_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_claims_paper_id'), 'research_claims', ['paper_id'], unique=False)
    op.create_index(op.f('ix_research_claims_workspace_id'), 'research_claims', ['workspace_id'], unique=False)
    op.create_table('research_methods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('dataset_used', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['research_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_methods_paper_id'), 'research_methods', ['paper_id'], unique=False)
    op.create_index(op.f('ix_research_methods_workspace_id'), 'research_methods', ['workspace_id'], unique=False)
    op.create_table('research_paper_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source_paper_id', sa.String(length=36), nullable=False),
    sa.Column('target_paper_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_paper_id'], ['research_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_paper_id'], ['research_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_paper_edges_source_paper_id'), 'research_paper_edges', ['source_paper_id'], unique=False)
    op.create_index(op.f('ix_research_paper_edges_target_paper_id'), 'research_paper_edges', ['target_paper_id'], unique=False)
    op.create_index(op.f('ix_research_paper_edges_workspace_id'), 'research_paper_edges', ['workspace_id'], unique=False)
    op.create_table('research_paper_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['research_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_paper_sections_paper_id'), 'research_paper_sections', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_paper_sections_paper_id'), table_name='research_paper_sections')
    op.drop_table('research_paper_sections')
    op.drop_index(op.f('ix_research_paper_edges_workspace_id'), table_name='research_paper_edges')
    op.drop_index(op.f('ix_research_paper_edges_target_paper_id'), table_name='research_paper_edges')
    op.drop_index(op.f('ix_research_paper_edges_source_paper_id'), table_name='research_paper_edges')
    op.drop_table('research_paper_edges')
    op.drop_index(op.f('ix_research_methods_workspace_id'), table_name='research_methods')
    op.drop_index(op.f('ix_research_methods_paper_id'), table_name='research_methods')
    op.drop_table('research_methods')
    op.drop_index(op.f('ix_research_claims_workspace_id'), table_name='research_claims')
    op.drop_index(op.f('ix_research_claims_paper_id'), table_name='research_claims')
    op.drop_table('research_claims')
    op.drop_index(op.f('ix_research_analysis_jobs_workspace_id'), table_name='research_analysis_jobs')
    op.drop_index(op.f('ix_research_analysis_jobs_paper_id'), table_name='research_analysis_jobs')
    op.drop_table('research_analysis_jobs')
    op.drop_index(op.f('ix_research_papers_workspace_id'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_slug'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_doi'), table_name='research_papers')
    op.drop_table('research_papers')
    op.drop_index(op.f('ix_research_insights_workspace_id'), table_name='research_insights')
    op.drop_table('research_insights')
    # ### end Alembic commands ###
